### ISSUE TITLE
Tutorials link missing in V3 website

### ISSUE THREAD

**Issue by HumpyBlumpy** [ITensor/website#51]
The link to Tutorials is missing on the C++v3 page. It appears only on C++v2.

**Comment by emstoudenmire** [comment]
Thank you for the bug report, but actually, the reason the link appears is that (1) we have not upgraded all of the tutorials to use version 3 of ITensor and (2) we are thinking of reorganizing the documentation anyway, and adapting most of the tutorial material into the ITensor Book section.
