### ISSUE TITLE
Point to v3.1.1 on homepage

### ISSUE THREAD

**Issue by mtfishman** [ITensor/website#54]
@emstoudenmire, could you have the homepage point to v3.1.1? It has an important bugfix for the `removeQNs(ITensor)` function.

It also has a few other improvements, like that `svd` now doesn't truncate by default (which it was doing accidentally before) and `Cutoff=0` now truncates singular values that are exactly zero.

Thanks,
Matt

**Comment by emstoudenmire** [comment]
Just updated, including the change log. Good updates!
